---

- name: Add docker repo key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "p80.pool.sks-keyservers.net"
    state: present
  sudo: yes

- name: Add docker repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ansible_distribution|lower}}-{{ansible_distribution_release|lower}} main"
    state: present
  sudo: yes

- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  sudo: yes
  with_items:
    - python-pip
    - "linux-image-extra-{{ ansible_kernel }}"
    - docker-engine


